# Generated by Django 3.0 on 2024-11-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'managed': False, 'verbose_name_plural': 'adresses'},
        ),
    ]
