# Generated by Django 3.0 on 2024-11-12 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # on supprime les models de l'app "oc_lettings_site"
            state_operations=[
                migrations.DeleteModel(
                    name='Address',
                ),
                migrations.DeleteModel(
                    name='Letting',
                ),
                migrations.DeleteModel(
                    name='Profile',
                ),
            ],
            # on renomme les tables
            database_operations=[
                migrations.AlterModelTable(
                    name='Address',
                    table='lettings_address',
                ),
                migrations.AlterModelTable(
                    name='Letting',
                    table='lettings_letting',
                ),
                migrations.AlterModelTable(
                    name='Profile',
                    table='profiles_profile',
                ),
            ],
        ),
    ]
