name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # checkout du code source
      - name: Checkout code
        uses: actions/checkout@v4

      # param Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # install des dépendances
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Linting (flake8)
      - name: Run Flake8 Linting
        run: |
          flake8 src/

      # Tests (pytest) et coverage
      - name: Run Tests and coverage
        id: coverage
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          coverage run --source=src -m pytest
          coverage report
          coverage html
          coverage xml
          coverage report --fail-under=80

      # publication du rapport coverage HTML en tant qu'artefact
      - name: upload Coverage Report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov/

      # vérification du seuil de coverage
      - name: Check Coverage > 80%
        if: failure()
        run: echo "Pipeline stopped due to coverage under 80%"
        continue-on-error: false

      # Generation de la doc avec Sphinx
      - name: Build Documentation with Sphinx
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          pip install -r docs/requirements.txt
          sphinx-apidoc -o docs/source/ src/ --no-toc -f "**/migrations/**" "**/tests/**" "*manage*"
          sphinx-build -b html docs/source/ docs/_build/html

      # publication de la documentation (artefact)
      - name: Upload Documentation
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-docs
          path: docs/_build/html/

      # Publication de la documentation sur Read the Docs
      - name: Init Read the Docs Build
        env:
          READTHEDOCS_PROJECT: ${{ vars.READTHEDOC_PROJECT_NAME }}
          READTHEDOCS_API_TOKEN: ${{ secrets.READTHEDOCS_API_TOKEN }}
        run: |
          curl -X POST -H "Authorization: Token $READTHEDOCS_API_TOKEN" -d '{"branch": "main"}' https://readthedocs.org/api/v3/projects/${{ secrets.READTHEDOC_PROJECT_NAME }}/versions/main/builds/

      # Construire l'image Docker si les tests réussissent
      - name: Build Docker Image
        if: success()
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/oc-lettings-site:${{ github.sha }} .
          docker tag ${{ vars.DOCKERHUB_USERNAME }}/oc-lettings-site:${{ github.sha }} ${{ vars.DOCKERHUB_USERNAME }}/oc-lettings-site:latest

          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/oc-lettings-site:${{ github.sha }} .
          docker tag ${{ vars.DOCKERHUB_USERNAME }}/oc-lettings-site:${{ github.sha }} ${{ vars.DOCKERHUB_USERNAME }}/oc-lettings-site:latest

      # connexion à Docker Hub
      - name: Login to Docker Hub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # pousser l'image sur Docker Hub
      # on pousse 2 versions pour la tracabilité (garder le hash)
      - name: Push Docker Image
        if: success()
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/oc-lettings-site:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/oc-lettings-site:latest

      # deployement sur Render
      - name: Deploy to Render
        if: success()
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

      # On verifie l'accès (endpoint /health), 3 essais
      - name: Check Health Endpoint
        run: |
          APP_URL="https://oc-lettings-site-hlhz.onrender.com/health/"
          MAX_RETRIES=3
          RETRY_DELAY=60

          for i in $(seq 1 $MAX_RETRIES); do
            STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" $APP_URL)
            if [ "$STATUS_CODE" -eq 200 ]; then
              echo "Health check passed on attempt #$i with status code $STATUS_CODE"
              exit 0
            else
              echo "Health check failed on attempt #$i with status code $STATUS_CODE. Retrying in $RETRY_DELAY seconds..."
              sleep $RETRY_DELAY
            fi
          done

          echo "Health check failed after $MAX_RETRIES attempts"
          exit 1
